CREATE DATABASE MYHOSPITAL;
USE MYHOSPITAL;

CREATE TABLE HOSPITAL(
   HID   INT			NOT NULL,
   HNAME VARCHAR (40)   NOT NULL,
   HCITY  VARCHAR (40)	NOT NULL,
   PRIMARY KEY (HID)
);

CREATE TABLE DEPARTMENT(
	DEPID INT 			NOT NULL,
    DEPNAME VARCHAR(40),
    HID INT,
    FOREIGN KEY(HID) REFERENCES HOSPITAL(HID),
    PRIMARY KEY(DEPID)
);

CREATE TABLE DOCTOR(
	DID INT				NOT NULL,
    DNAME VARCHAR(40)	NOT NULL,
    SALARY int			NOT NULL,
    DEPID INT			NOT NULL,
    FOREIGN KEY(DEPID) REFERENCES DEPARTMENT(DEPID),
	PRIMARY KEY (DID)
);

CREATE TABLE PATIENT(
	PATID INT			NOT NULL,
    PATNAME VARCHAR(40)	NOT NULL,
    PATCITY VARCHAR(40)	NOT NULL,
    PATCONTACT CHAR(10),
    ADMIT_DATE DATE,
    DISCHARGE_DATE DATE,
    DID INT,
    FOREIGN KEY(DID) REFERENCES DOCTOR(DID),
    PRIMARY KEY(PATID)
);
